branch-defaults:
  default:
    environment: Assignment3-dev
    group_suffix: null
global:
  application_name: Assignment3
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: null
